[tools]
cilium-cli = "0.18.8"
doppler = "3.75.1"
flux2 = "2.7.5"
gh = "2.83.1"
"github:budimanjojo/talhelper" = "3.0.41"
"github:holos-run/holos" = "0.105.1"
helm = "4.0.1"
talosctl = "1.11.5"
terraform = "1.14.1"
timoni = "0.25.2"

[tasks.render]
run = "cd {{ config_root }}; rm -rf deploy; holos render platform"

[tasks.mergeall]
run = "gh pr list --json number -q '.[].number' | xargs -I% gh pr merge % -s -d"
