apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: system-upgrade-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: system-upgrade-controller
    helm.sh/chart: app-template-4.2.0
  name: system-upgrade-controller
  namespace: system-upgrade
spec:
  roles:
  - os:admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: system-upgrade-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: system-upgrade-controller
    helm.sh/chart: app-template-4.2.0
  name: system-upgrade-controller
  namespace: system-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: system-upgrade-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: system-upgrade-controller
    helm.sh/chart: app-template-4.2.0
  name: system-upgrade-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: system-upgrade-controller
  namespace: system-upgrade
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/controller: system-upgrade-controller
    app.kubernetes.io/instance: system-upgrade-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: system-upgrade-controller
    helm.sh/chart: app-template-4.2.0
  name: system-upgrade-controller
  namespace: system-upgrade
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: system-upgrade-controller
      app.kubernetes.io/instance: system-upgrade-controller
      app.kubernetes.io/name: system-upgrade-controller
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: system-upgrade-controller
        app.kubernetes.io/instance: system-upgrade-controller
        app.kubernetes.io/name: system-upgrade-controller
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: SYSTEM_UPGRADE_CONTROLLER_LEADER_ELECT
          value: "true"
        - name: SYSTEM_UPGRADE_CONTROLLER_NAME
          value: system-upgrade-controller
        - name: SYSTEM_UPGRADE_CONTROLLER_NAMESPACE
          value: system-upgrade
        - name: SYSTEM_UPGRADE_CONTROLLER_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SYSTEM_UPGRADE_JOB_BACKOFF_LIMIT
          value: "99"
        - name: SYSTEM_UPGRADE_JOB_PRIVILEGED
          value: "false"
        image: docker.io/rancher/system-upgrade-controller:v0.16.3
        name: app
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: system-upgrade-controller
